### ISSUE TITLE
[FEATURE REQUEST] Support pylint 3.0.0 or more

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [prospector-dev/prospector#670] opened 2024-10-04 06:07 UTC
Folow-up to #642 and #643 , we can upgrade to pylint 3.0+ once requirements-detector is compatible with astroid 3.0+, see https://github.com/landscapeio/prospector/issues/641#issuecomment-2392332978

**Comment by carlio** [comment] 2024-10-04 09:41
Not sure why it automatically closed this as "completed"...

**Comment by carlio** [comment] 2024-10-04 09:55
@Pierre-Sassoulas requirements-detector 1.3.0 is released now with the astroid dependency set to '>=2.0'

**Comment by carlio** [comment] 2024-10-04 10:12
Ok, 1.3.1 requirements-detector is released with the updated astroid version constraints

**Comment by Pierre-Sassoulas** [comment] 2024-10-04 10:36
Amazing, thank you @carlio

**Comment by Pierre-Sassoulas** [comment] 2024-10-04 10:41
> Not sure why it automatically closed this as "completed"...

You can close issue from other projects inside an organization, automatically using the keyword fix/close in the commit message which is what happened with ``fix https://github.com/landscapeio/prospector/issues/670`` in the commit message merged in requirements-detector :)

**Comment by ryancausey** [comment] 2024-10-05 05:38
It looks like there are asteroid crashes while running pylint on Python 3.12 due to needing fixes in Pylint >= 3 and Asteroid >= 3. Thus, I believe this change is needed before full Python 3.12 support can be achieved.

**Comment by valeriupredoi** [comment] 2024-10-07 14:21
I've just pushed `requirements-detector==1.3.1` to conda-forge via https://github.com/conda-forge/requirements-detector-feedstock/pull/23 and now (well, once the new 1.3.1 package is available in the registry) we can rebuild `prospector==1.11` with the new requirements-detector in https://github.com/conda-forge/prospector-feedstock/pull/49 :+1: :beer: Excellent work @Pierre-Sassoulas and @carlio :beers:

**Comment by valeriupredoi** [comment] 2024-10-07 14:33
agh nevermind 1.11 - I just saw you guys released a v1.12 an hour ago, I'll crack on with 1.11 at the feedstock, then I'll check and update the bot's PR for 1.12 too, so that gets released timely too :+1:

**Comment by Pierre-Sassoulas** [comment] 2024-10-07 14:50
There's no way to make pylint work for python 3.12 without the work on compat for pylint 3.0 done for prospector 1.12. (pylint won't work for python 3.12 before pylint 3.0 and prospector won't work with pylint 3.0+ before prospector 1.12).

**Comment by valeriupredoi** [comment] 2024-10-07 14:55
@Pierre-Sassoulas I just saw that via the [failed CI at feedstock](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1048105&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=919) - shall I just skip 1.11 release and do 1.12 instead?

**Comment by valeriupredoi** [comment] 2024-10-07 16:03
OK folks, got us a working v1.12.0 package via https://github.com/conda-forge/prospector-feedstock/pull/49 - only hitch is from my comment https://github.com/conda-forge/prospector-feedstock/pull/49#issuecomment-2397314558 ie:

OK table of troubles: only `pylint-django>=2.5.5` (latest, 2.5.5) accepts `pylint>=3` but said `pylint-django` needs `pylint-plugin-utils >=0.8` so I plugged them in, the problem is the PyPI package `prospector==1.12` got built with `pylint-plugin-utils <0.8` so `pip check` throws a wobbly. `pip check` is a bit old fashioned IMHO, if the conda package gets built with conda-forge dependencies, so no biggie here

If there is no issue with this @Pierre-Sassoulas @carlio then that PR is ready to be merged and that means Python 3.12.7, pylint 3.3.1 support, and other dependencies [as per the build log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1048139&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3) :partying_face:

**Comment by carlio** [comment] 2024-10-07 16:07
The guilty line is https://github.com/prospector-dev/prospector/blob/master/pyproject.toml#L45 - it'd be easy to increase that version.

However, I cannot remember if pylint-plugin-utils is used directly by prospector. I'll have a look later, I'm about to get on a plane so I'll be away, but I suspect that removing that dependency might make more sense than pinning it - check if it's used first. I'll have a look myself later if nobody else gets to it in time.

**Comment by valeriupredoi** [comment] 2024-10-07 16:08
good call @carlio - I'll have a look now :+1:

**Comment by valeriupredoi** [comment] 2024-10-07 16:42
OK folks prospector=1.12 has been released into the wild (conda-forge :grin: )

**Comment by Pierre-Sassoulas** [comment] 2024-10-07 21:05
Are you the person in charge of the conda release @valeriupredoi ? We should probably publish the same thing than what we release on pypi on conda (using the same pipeline). https://github.com/prospector-dev/prospector/blob/master/.github/workflows/release.yml

**Comment by valeriupredoi** [comment] 2024-10-08 11:36
I'll actually open a new issue, I remembered there is that `pylint-plugin-utils` issue too, apols for yapping on in here :beer:

**Comment by valeriupredoi** [comment] 2024-10-08 11:49
> > most them stemming from Prospector's pin of flake8 <7 - is that something we can relax?
> 
> Yes since we dropped python 3.7 I think

excellent! From a purely dependency table pov that should be fine (I'll test when I build the build=1 fro 1.12 but I don't see any issues as of now), was concerned that `flake8>=7` may rub against some of Prospector's functionality :+1:

**Closed** 2024-10-11 12:31 UTC
Labels: enhancement
